default: all

PDF_FILES = gsiopenssh.pdf
SUBDIRS=admin developer mig pi qp rn user

PDFS=admin/gsiopensshAdminGuide.pdf user/gsiopensshUserGuide.pdf developer/gsiopensshDeveloperGuide.pdf mig/gsiopensshMigratingGuide.pdf qp/gsiopensshQualityProfile.pdf rn/gsiopensshReleaseNotes.pdf

gsiopenssh.pdf: $(PDFS)

TOPDIR=..
include $(TOPDIR)/rules.mk
