default: all

PDF_FILES = gsic.pdf
SUBDIRS=admin developer key mig pi qp rn user

PDFS=admin/gsicAdminGuide.pdf user/gsicUserGuide.pdf developer/gsicDeveloperGuide.pdf mig/gsicMigratingGuide.pdf qp/gsicQualityProfile.pdf rn/gsicReleaseNotes.pdf

gsic.pdf: $(PDFS)

TOPDIR=..
include $(TOPDIR)/rules.mk
