dist: focal
arch:
  - ppc64le

script:
  - sudo apt-get update
  - sudo apt-get -y install asciidoctor rsync
  - sleep 5
  - travis-ci/build-site.sh

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep built pages
  skip-cleanup: true
  # Directory where your generated files are located
  local_dir: html
  deploy-key: /tmp/travis/github_deploy_key
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy
  target_branch: gh-pages
  on:
    branch: adoc
before_install:
  - touch /tmp/travis/github_deploy_key
  - chmod 0600 /tmp/travis/github_deploy_key
  - openssl aes-256-cbc -K $encrypted_2d31d0fdb65c_key -iv $encrypted_2d31d0fdb65c_iv
    -in travis-ci/github_deploy_key.enc -d > /tmp/travis/github_deploy_key
