[[gt]]
:doctype: article
= Grid Community Toolkit =

The Grid Community Toolkit (GCT) is an open-source fork of the venerable link:http://toolkit.globus.org/toolkit[Globus Toolkit] created by the Globus Alliance.
The GCT was created in response to the link:https://github.com/globus/globus-toolkit/blob/globus_6_branch/support-changes.md[end-of-support] of the Globus Toolkit in January 2018.

== GCT 6.0 Release Manuals ==

The following documents are good places to start with GCT 6.0:

* For everyone: 
** link:./rn/index.html[GCT6.0 Release Notes]
** link:./appendices/commands/index.html[GCT Commands]
* For system administrators and those installing GCT: 
** link:./admin/install/index.html[Installation Guide]
** link:./admin/quickstart/index.html[Quickstart]
* For End Users: 
** link:./rn/index.html#java-api-download[Java API Download]
* For Developers: 
** link:./appendices/developer/index.html[GCT Developer's Guide]

GCT 6.0 release manuals are divided into the following areas:

* ** link:./gridftp/index.html[GridFTP] for Data Management **
+
GridFTP provides high-performance and reliable data transport.

* ** link:./gram5/index.html[GRAM5] for Jobs Management **
+
The Grid Resource Allocation and Management (GRAM5) interface as a basic
mechanism for initiation, monitoring, management, scheduling, and/or
coordination of remote computations.

* ** link:./gsic/index.html[GSI C], link:./myproxy/index.html[MyProxy] and link:./gsiopenssh/index.html[GSI-OpenSSH] for Grid Security **
+
These components establish the identity of users or services (authentication),
protect communications, and determine who is allowed to perform what actions
(authorization), as well as manage user credentials.

* ** Other Components **
+
GCT 6 also includes a set of link:./ccommonlib/index.html[C Common libraries]
needed for building grid infrastructure, link:./xio/index.html[XIO], a
sophisticated and extensible I/O library suitable for the dynamic needs of grid
applications and link:./simpleca/index.html[SimpleCA], a simple certificate
authority available for testing purposes.
