[[rn,Release Notes]]
:doctype: article
= GCT 6.2 Release Notes =

include::../wascopied_frag.adoc[]

ifdef::backend-html5[link:../index.html[GCT] -> Release Notes]
  
[[rn-intro]]
== Introduction ==

The Grid Community Toolkit (GCT) development team is pleased to make the 6.2 release of the
GCT available for download.

By following the link:../admin/quickstart/index.html[Quickstart]
guide, you can easily install and setup a full GCT environment in
minutes.

Highlights of this release include:

* Overall
** The Grid Community Forum took over development of the former Globus - now - Grid Community Toolkit
** Integration of community patches and patches from the Globus team
** Deactivation of usage statistics collection by default
* GridFTP
include::../gridftp/GridFTP_Change_Summary_Highlights_Frag.adoc[]
* C Common Libraries
include::../ccommonlib/C_Common_Libraries_Change_Summary_Highlights_Frag.adoc[]

To view details for each component, see link:#rn-bycomponents[Release Notes by
Component].
 
[[rn-software]]
== Obtaining and Installing Software ==

To download this release, go to the link:https://github.com/gridcf/gct/releases/latest[GCT Releases page on GitHub].

For information on installing this release, go to the
link:../admin/install/index.html[6.2 Installation Guide].


:leveloffset: 1
include::../Java_API_Download.adoc[]
:leveloffset: 0

 
[[rn-platform]]
== Platform Notes ==

Check out platform-specific installation issues
link:../admin/install/index.html#gtadmin-platform[here].

 
[[rn-documentation]]
== Documentation ==

Use the documentation which starts link:../index.html[here].

Feel free to offer any suggestions or feedback using
http://jira.globus.org[JIRA] (the "Documentation" project). 

 
[[rn-support]]
== Support ==

An overview on GCT support can be found
http://www.globus.org/toolkit/support.html[here].

 
[[rn-license]]
== Licensing ==

The Grid Community Toolkit is distributed and licensed for use under the terms
of the https://www.apache.org/licenses/LICENSE-2.0[Apache License,
Version 2.0].

To view the licenses of the 3rd party software used by the developers of
the Grid Community Toolkit, see link:../licenses/3rd_party/index.html[3rd Party Licenses].

 
[[rn-usagestats]]
== Usage Statistics ==

This is deactivated by default since GCT 6.2. For more information about usage
statistics collection, see link:../Usage_Stats.html[Usage Statistics Collection].

 
[[rn-bycomponents]]
== Release Notes by Component ==

* link:../gridftp/rn/index.html[GridFTP]
* link:../gram5/rn/index.html[GRAM5]
* Security
** link:../gsic/rn/index.html[GSI C]
** link:../simpleca/rn/index.html[SimpleCA]
** link:../myproxy/rn/index.html[MyProxy]
** link:../gsiopenssh/rn/index.html[GSI-OpenSSH]
* Common Runtime Components
** link:../xio/rn/index.html[XIO]
** link:../ccommonlib/rn/index.html[C Common Libraries]
