[[gridftpMig,Migrating Guide]]
:doctype: article
= GT 6.0 Migrating Guide for GridFTP =

  
--
The following provides available information about migrating from
previous versions of the Globus Toolkit.

 
--

[[gridftp-migrating-GT5.0]]
== Migrating GridFTP from GT5.0 ==

FIXME

 
[[gridftp-migrating-GT4.2]]
== Migrating GridFTP from GT4.2 ==

FIXME

 
[[gridftp-migrating-GT3-GT4]]
== Migrating GridFTP from GT3 or GT4.0 ==

If you are running GT 3.0.0 or greater, the migration for GridFTP is
relatively painless. There were only new features added. No changes were
made to the existing protocol or APIs, so any existing client or
application built using our client APIs will work unchanged. You may
install new clients and servers on an as-opportunity-permits basis and
will have no problems. Any combination of old/new client/server will
work.

To upgrade your server, either install it in a $GLOBUS_LOCATION
different than the GT 3 installation (either as part of an entire GT 4
installation or by doing just ++make gridftp++). Alternately, you can
statically link the new server to avoid versioning issues and replace
the existing executable. The configuration files are very different, so
you will need to update the configuration.

To upgrade your client, simply build the client and use the new client
as you would the old one. 

Below is a list of new functionality available in GT 3.2 and higher
(note that the MLST/MLSD feature is used by RFT in GT 3.2 and higher and
is required if you want to be able to specify a directory to move):

New Functionality in 3.2:




* Server Improvements 

* Structured File Info

* MLST, MLSD

* checksum support

* chmod support

* globus-url-copy changes 

* File globbing support

* Recursive dir moves

* RFC 1738 support

* Control of restart

* Control of DC security


 
include::../GridFTP_Migrating_GT2_Frag.txt[]

  