
[[gram5-lrma-tutorial-perl-changes]]
=== Changes from Previous Versions ===


==== Changes in GT 5.2 ====

GRAM5 is now designed to work as a native debian or RPM package, with
default configuration being done at configuration time, so the setup
script description has been removed. 


==== Changes in GT 5.0 ====

GRAM5 is based again on the C code base used for GRAM2 (also known as
Pre-WS GRAM). The SEG module interface from GRAM4 is retained and
optionally used by GRAM5. The GRAM job manager will avoid reloading the
GRAM LRM Adapter script for each operation, so all variables not
intended to be global state in the Perl LRM Adapter module must be
lexically scoped, or state will leak between jobs and cause potentially
cause problems. 


==== Changes in GT 4.0 ====


===== Module Methods =====

The GT-4.0 ws-GRAM service only calls a subset of the Perl methods which
were used by the pre-ws GRAM services. Most importantly for script
implementors, the polling method is no longer used. Instead, the
scheduler-event-generator monitors jobs to signal the service when job
change changes occur. Staging is now done via the Reliable File Transfer
service, so the file_stage_in and file_stage_out methods are no longer
called. Schedulers typically did not implement the staging methods, so
this shouldn't affect most scheduler modules. 

That being said, scheduler implementers which would like to have their
scheduler both with pre-ws GRAM and WS-GRAM should definitely implement
the poll() method described in the pre-WS version of this tutorial.


===== GASS Cache =====

The GT-4.0 ws-GRAM service does not use the GASS cache for storing
temporary files or for staging files. 


==== Changes in GT 3.2 ====

In GT 3.2, additional error message context info was added. Scripts can
optionally add one of these fields to the return hash from an operation
to provide extra error information to the client: 

**GT3_FAILURE_MESSAGE**::
     Error message from underlying script processing indicating what caused a job request to fail

**GT3_FAILURE_TYPE**::
     One of ++filestagein++, ++filestageout++, ++filestageinshared++, ++executable++, or ++stdin++ indicating what job request element caused a staging fault.

**GT3_FAILURE_SOURCE**::
     Source URL or file for a failed staging operation

**GT3_FAILURE_DESTINATION**::
     Destination URL or file for a failed staging operation


