[[globus-scheduler-event-generator]]
= GLOBUS-SCHEDULER-EVENT-GENERATOR(8) =
:doctype: manpage
:man source: University of Chicago

== NAME ==
globus-scheduler-event-generator - Process LRM events into a common format for use with GRAM

== SYNOPSIS ==
**++globus-scheduler-event-generator++** ++-s++ 'LRM'  +
 +
 [++-t++ 'TIMESTAMP'] [++-d++ 'DIRECTORY']  +
 +
 [++-b++ ] [++-p++ 'PIDFILE'] 

== Description ==

The **++globus-scheduler-event-generator++** program processes
information from a local resource manager to generate LRM-independent
events which GRAM can use to track job state changes. Typically, the
**++globus-scheduler-event-generator++** is started at system boot time
for all LRM adapters which have been installed. The only required
parameter to **++globus-scheduler-event-generator++** is '-s ', which
indicates what LRM-specific module to load. A list of available modules
can be found by using the **++globus-scheduler-event-generator-admin
++** command. 

Other options control how the **++globus-scheduler-event-generator++**
program runs and where its output goes. These options are: 

**-t 'TIMESTAMP'**::
     Start processing events which start at 'TIMESTAMP' in seconds since the
UNIX epoch. If not present, the **++globus-scheduler-event-generator++**
will process events from the time it was started, and not look for
historical events.

**-d 'DIRECTORY'**::
     Write the event log to files in 'DIRECTORY', instead of printing them to
standard output. Within 'DIRECTORY', logs will be named by the time when
they were created in 'YYYYMMDD' format.

**-b**::
     Run the **++globus-scheduler-event-generator++** program in the
background.

**-p 'PIDFILE'**::
     Write the process-id of **++globus-scheduler-event-generator++** to
'PIDFILE'.



== Files ==



**++/var/lib/globus/globus-seg-LRM/YYYYMMDD++**::
     LRM-independent event log generated by **++globus-scheduler-event-generator++**



== See Also ==

++globus-scheduler-event-generator-admin(8)++, ++globus-job-manager(8)++


