[[q-prereq]]
== Prerequisites ==

The Grid Community Toolkit 6.2 is available as a set of RPM packages provided
by EPEL and Fedora package repositories and Debian packages provided by Debian
and Ubuntu package repositories for Linux distributions as well as a source
installer for the whole GCT and separate source packages for each GCT component
provided by the GridCF from 
https://repo.gridcf.org/gct6/[our repository] 
which can be used both on Linux and on other operating systems.
Please see the bottom of the
https://github.com/gridcf/gct/releases/latest[GCT release page] 
for information about the supported Linux distributions.
In this quickstart, we will be installing RPM packages. Thus, it is a
prerequisite for following this quickstart that you are running a distribution
for which RPMs are available. If you are running a supported Debian or Ubuntu
system, the process is very similar, but you'll need to use the **++apt[-get]++** 
command or similar tools to install the packages. For the source installer,
there is more work involved, and you'll need to consult 
link:../install/index.html[the full installation guide].

First, we will set up our system to use the EPEL package
repository. This repository contains the GCT software packages for Linux
distributions like Red Hat Enterprise Linux (RHEL) 7, 8 and 9, Community
Enterprise Operating System (CentOS) 7 and CentOS Stream 8 and 9, RockyLinux 8
or Scientific Linux 7. If your distribution has GCT 6.2 packages within its
default repositories - like Fedora has - you can skip to the next section.

The respective EPEL repo RPMs for the respective OS versions are linked from 
https://docs.fedoraproject.org/en-US/epel/[the EPEL documentation website].

To install binary RPMs, you first need to install the EPEL repo RPM matching
your OS. E.g. like so:

--------
root# yum install epel-release
--------

...for CentOS 7 which has it included in its default repositories.

For other OS versions follow 
https://docs.fedoraproject.org/en-US/epel/#_quickstart[the EPEL quickstart documentation].


For Fedora and also Debian and Ubuntu the GCT packages are included in the
default package repositories, so no further action is required there to be able
to install GCT packages.


You can now use your operating system's packaging tools: **++yum++** (or 
**++dnf++**) or **++apt[-get]++**, to install the GCT components.

