[[gridftp-usage]]
== Usage statistics collection by the Globus Alliance ==
indexterm:[usage statistics for GridFTP]


[[gridftp-usage-stats]]
=== GridFTP-specific usage statistics ===

The following GridFTP-specific usage statistics are sent in a UDP packet
at the end of each transfer, in addition to the standard header
information described in the
link:/toolkit/docs/{$shortversion}/{$version}/Usage_Stats.html[Usage
Stats] section. 

* Start time of the transfer

* End time of the transfer

* Version string of the server

* TCP buffer size used for the transfer

* Block size used for the transfer

* Total number of bytes transferred

* Number of parallel streams used for the transfer

* Number of stripes used for the transfer

* Type of transfer (STOR, RETR, LIST)

* FTP response code -- Success or failure of the transfer



[NOTE]
--
The client (globus-url-copy) does NOT send any data. It is the **servers** that send the usage statistics.
--


We have made a concerted effort to collect only data that is not too
intrusive or private and yet still provides us with information that
will help improve and gauge the usage of the GridFTP server.
Nevertheless, if you wish to disable this feature for GridFTP only, use
the '-disable-usage-stats' option of
link:../../gridftp/admin/index.html#globus-gridftp-server[globus-gridftp-server].
Note that you can disable transmission of usage statistics globally for
all C components by setting "GLOBUS_USAGE_OPTOUT=1" in your environment.


Also, please see our
link:/toolkit/docs/latest-stable/Usage_Stats.html[policy statement] on
the collection of usage statistics. 

