[[gridftp-command-client]]
:doctype: book

:leveloffset: 1

include::globus-url-copy.txt[]

:leveloffset: 0

[[globus-url-copy-interactiveclients]]
== Interactive clients for GridFTP ==

The Globus Project does **not** provide an interactive client for
GridFTP. Any normal FTP client will work with a GridFTP server, but it
cannot take advantage of the advanced features of GridFTP. The
interactive clients listed below take advantage of the advanced features
of GridFTP.

There is no endorsement implied by their presence here. We make no
assertion as to the quality or appropriateness of these tools, we simply
provide this for your convenience. We will **not** answer questions,
accept bugs, or in any way shape or form be responsible for these tools,
although they should have mechanisms of their own for such things. 

UberFTP was developed at the NCSA under the auspices of NMI and
TeraGrid:

* http://dims.ncsa.uiuc.edu/set/uberftp/download.html[NCSA UberFTP download]
* http://dims.ncsa.uiuc.edu/set/uberftp/userdoc.html[UberFTP User's Guide]
