default: all

PDF_FILES = ccommonlib.pdf
SUBDIRS=developer mig pi qp rn

PDFS=developer/ccommonlibDevelopersGuide.pdf mig/ccommonlibMigratingGuide.pdf qp/ccommonlibQualityProfile.pdf rn/ccommonlibReleaseNotes.pdf

ccommonlib.pdf: $(PDFS)

TOPDIR=..
include $(TOPDIR)/rules.mk
