default: all

PDF_FILES = gram5.pdf
SUBDIRS=admin developer key mig pi qp rn user

PDFS=admin/gram5AdminGuide.pdf user/gram5UserGuide.pdf developer/gram5DeveloperGuide.pdf mig/gram5MigratingGuide.pdf qp/gram5QualityProfile.pdf rn/gram5ReleaseNotes.pdf

gram5.pdf: $(PDFS)

TOPDIR=..
include $(TOPDIR)/rules.mk
