default: all

PDF_FILES = xio.pdf
SUBDIRS=admin developer mig pi qp rn

PDFS=admin/xioAdminGuide.pdf developer/xioDeveloperGuide.pdf mig/xioMigratingGuide.pdf qp/xioQualityProfile.pdf rn/xioReleaseNotes.pdf

xio.pdf: $(PDFS)

TOPDIR=..
include $(TOPDIR)/rules.mk
