
[[gtadmin-install]]
== Installing GCT 6.2 ==


[[install-bininst]]
=== Installing Binary Packages ===

:leveloffset: 1

include::../quickstart/prereq_frag.adoc[]

:leveloffset: 0

[[install-toolkit]]
==== Installing the Toolkit on Linux ====

The components of the toolkit can be installed separately, or all at
once. This section will show how to install various components, on both
RPM based and Debian based Linux systems.

For Fedora or Red Hat-based systems, use the **++yum++** or **++dnf++** commands
to install the GCT components and their dependencies. For SUSE Linux
distributions, use **++zypper++**. For Debian-based systems, used the
**++apt[-get]++** or **++aptitude++** commands.

For example, to install the GridFTP client tools, do the following for
Red Hat-based systems:

--------
root# yum install \
    globus-common-progs globus-gsi-cert-utils-progs globus-ftp-client globus-gass-copy-progs globus-proxy-utils
--------

Do the following for Debian-based systems: 

--------
root# apt-get install \
    globus-common-progs globus-gsi-cert-utils-progs globus-ftp-client globus-gass-copy-progs globus-proxy-utils
--------


===== Updating a GCT Installation =====

For the GCT the package repositories in general always include the GCT component
versions that were included in the latest available GCT version, except for
Debian, where the package repositories for the stable distributions include the
GCT component versions that were included in the latest GCT version that was
available before the freeze for the respective stable version of Debian took
place. Debian unstable (aka Sid) instead always includes the GCT component
versions that were included in the latest available GCT version like the other
Linux distributions.

In addition fixes for broken GCT packages or security fixes for GCT components
are included in the package repositories **also** in between GCT releases.

In general updating a GCT installation can hence be done via **++yum++** (or
**++dnf++**) or **++apt[-get]++** manually or happens automatically during
unattended OS upgrades.


[[gtadmin-installation-from-source-installer]]
=== Installation from Source Installer ===

[NOTE]
--
Installing using the Source Installer is only recommended on platforms
for which native packages are not available. If you are installing onto
a Red Hat or Debian based Linux system, please see the section above.

--

:leveloffset: 2

include::prereq_frag.adoc[]

:leveloffset: 0

==== Installing from Source Installer ====

. Create a user named **++globus++**. This non-privileged user will be
used to perform administrative tasks, deploying services, etc. Pick an
installation directory, and make sure this account has read and write
permissions in the installation directory.
+
[TIP]
--
You might need to create the target directory as **++root++**, then
chown it to the **++globus++** user: 

--------
root# mkdir <INSTALL_DIR>
root# chown globus:globus <INSTALL_DIR>
--------


--
+
[IMPORTANT]
--
If for some reason you do **not** create a user named **++globus++**, be
sure to run the installation as a **non-root** user. In that case, make
sure to pick an install directory that your user account has write
access to. 

--

. Download the required software noted in link:#gtadmin-prereq[Software
Prerequisites].

. The Grid Community Toolkit Source Installer sets the installation directory by
default to ++/usr/local/globus-6++, but you may replace ++/usr/local/globus-6++
with whatever directory you wish to install to, by setting the prefix when you
configure.
+
As the globus user, run:
+
--------
globus% ./configure --prefix=<INSTALL_DIR>
--------
+
You can use command line arguments to **++./configure++** for a more custom
install.
+
For a full list of options, see **++./configure --help++**.

. The source installer will build all of the Grid Community Toolkit packages in
the default make rule. The following Makefile targets can be used to
build subsets of the Grid Community Toolkit: 
+
**ccommonlibs**::
     C Common Libraries

**gridftp**::
     GridFTP Client and Server

**gsi**::
     Security Libraries and Tools

**udt**::
     Globus XIO UDT Driver

**myproxy**::
     MyProxy Client and Server

**gsi-openssh**::
     GSI OpenSSH Client and Server

**gram5**::
     GRAM5 Client and Libraries

**gram5-server**::
     GRAM5 Service

**gram5-lsf**::
     GRAM5 LSF Adapter

**gram5-sge**::
     GRAM5 SGE Adapter

**gram5-slurm**::
     GRAM5 SLURM Adapter

**gram5-condor**::
     GRAM5 Condor Adapter

**gram5-pbs**::
     GRAM5 PBS Adapter

**gram5-auditing**::
     GRAM5 Auditing Support
+
Run:
+
--------
globus% make 
--------
+
Note that this command can take a while to complete. If you wish to have
a log file of the build, use **++tee++**:
+
--------
globus% make 2>&1 | tee build.log
--------
+
The syntax above assumes a Bourne shell. If you are using another shell,
redirect **++stderr++** to **++stdout++** and then pipe it to **++tee++**.

. To test the toolkit, or particular packages within the toolkit, run: 
+
--------
globus% make check
--------
+
or 
+
--------
globus% make <COMPONENT>-check
--------
+
where '<COMPONENT>' is the name of the package to test. As an example, you
could run 
+
--------
globus% make globus_gssapi_gsi-check
--------
+
to run the GSSAPI test programs.

. Finally, run:
+
--------
globus% make install
--------
+
This completes your installation. Now you may move on to the
configuration sections of the following chapters.
+
We recommend that you keep your installation up to date and always use
https://github.com/gridcf/gct/releases/latest[the latest version of the GCT].
You may also be interested in subscribing to the mailing lists listed under
**Contact** and **News** on
https://gridcf.org/[the GridCF website].


==== Updating an Installation ====

The updates available in the native packages described above are also
published as source packages in
https://repo.gridcf.org/gct6/[our repository].
To install update packages, follow their download link, untar
them, then configure them with the same prefix as your original
installation and install them as described above.

